//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashcards.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlashcardImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlashcardImage()
        {
            this.FlashcardTranslations = new HashSet<FlashcardTranslation>();
            this.FlashcardTranslations1 = new HashSet<FlashcardTranslation>();
        }
    
        public int FlashcardID { get; set; }
        public long FileID { get; set; }
    
        public virtual File File { get; set; }
        public virtual Flashcard Flashcard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlashcardTranslation> FlashcardTranslations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlashcardTranslation> FlashcardTranslations1 { get; set; }
    }
}
