//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashcards.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlashcardsEntities : DbContext
    {
        public FlashcardsEntities()
            : base("name=FlashcardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<FlashcardImage> FlashcardImages { get; set; }
        public virtual DbSet<Flashcard> Flashcards { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<FlashcardTranslation> FlashcardTranslations { get; set; }
        public virtual DbSet<UserFlashcardMemory> UserFlashcardMemories { get; set; }
        public virtual DbSet<TrainingSession> TrainingSessions { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<TrainingCard> TrainingCards { get; set; }
        public virtual DbSet<InternalReview> InternalReviews { get; set; }
        public virtual DbSet<ReviewCard> ReviewCards { get; set; }
    }
}
