//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashcards.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFlashcardMemory
    {
        public int FlashcardID { get; set; }
        public int LanguageID { get; set; }
        public long UserID { get; set; }
        public System.DateTime LastReviewTime { get; set; }
        public System.DateTime NextReviewTime { get; set; }
        public decimal Strength { get; set; }
    
        public virtual Flashcard Flashcard { get; set; }
        public virtual Language Language { get; set; }
    }
}
